
export const supaUrl = 'https://kenhdsibvgteaozomxax.supabase.co';

export const anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtlbmhkc2lidmd0ZWFvem9teGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjkzMDMsImV4cCI6MjA3MjM0NTMwM30.N881mgpV5je3HeUVdObN-DnardzAFtIEIwXuD4wxxQo';